print("### REQUEST TACTICAL DOLL ###") 
nama = str(input("Masukkan nama Tactical Doll: "))
firepower = float(input("Masukkan Firepower: "))
Rate_of_Fire = float(input("Masukkan Rate of Fire: "))
Accuracy = float(input("Masukkan Accuray: "))
Evasion = float(input("Masukkan Evasion: "))
evadmg_per_sekon = round((firepower * Rate_of_Fire) / 60, 2)
ce = int((30 * firepower) + (40 * (Rate_of_Fire ** 2) / 120) + (15 * (Accuracy + Evasion)))
print("\n### SUCCESS ###")
print(f"Firepower Kamu: {firepower}")
print(f"Rate of Fire kamu: {Rate_of_Fire}")
print(f"Accuracy kamu: {Accuracy}")
print(f"Evasion kamu: {Evasion}")
print(f"Damage per detik kamu: {evadmg_per_sekon}")
print(f"Combat Effectiveness kamu: {ce}")
print("=== PROGRAM SUCCESS ===")